### ISSUE TITLE
Should errors in shutdown be ignored?

### ISSUE THREAD

**Issue by alexcrichton** [steffengy/schannel-rs#19]
Over at tokio-tls we've got a [smoke test](https://github.com/tokio-rs/tokio-tls/blob/44a5c9edab1a53e5bec9b1ae00a5ec919b108f22/tests/smoke.rs#L616-L649) which just tests a simple TLS handshake and sending some bytes from a client to a server, but notably limits I/O reads/writes to only progress one byte at a time. This is intended to stress retry logic and ensure that at least most paths are covered.

Previously this test passed, but recently a change was made to properly issue a shutdown operation from the server side when it's done writing (the test just writes a bunch of bytes from the server to the client). This unfortunately has started making the test fail with schannel!

It looks like schannel is acknowledging a shutdown and [attempting to run its own](https://github.com/steffengy/schannel-rs/blob/6899374578f8de72dae72fcdd0cbfa304ac856cd/src/tls_stream.rs#L648-L650), but then during that function a WSAECONNRESET is received during a TCP write (b/c the other end has dropped at that point).

I'm curious, have you seen this before? Are you familiar with behavior like this? I'm not sure if this is a bug in the test (e.g. requiring a call here or there) or if it's a case where the error should be ignored. The test passes on OSX/Linux FWIW, but Windows (schannel) may just be exposing a surprising edge case.

In any case, thoughts would be welcome!

**Comment by sfackler** [comment]
Yeah! So, TLS shutdown is a two stage process - you send a shutdown notification to the other end, which then replies to acknowledge that. A "full" shutdown involves the full back-and-forth which ensures that both ends know that the session's been terminated. However, it is very common to only issue the shutdown alert and then call it a day (or on the receiving end immediately kill the connection without sending the response). This is explicitly allowed in the standard.

In addition, many implementations (including Hyper servers/clients right now) won't bother with a shutdown at all. This is a bummer since you can't reuse SSL sessions so we should fix that in the ecosystem at some point.

The moral of this story is that you probably should ignore errors in shutdown since it's a "best effort" kind of thing.

**Comment by sfackler** [comment]
OpenSSL gives you control over how much of the shutdown you perform, but Secure Transport does not, and I'm not sure about schannel since we drive so much of the logic ourselves.

**Comment by alexcrichton** [comment]
Oh ok! So in that case should I send a PR to [basically ignore errors here](https://github.com/steffengy/schannel-rs/blob/6899374578f8de72dae72fcdd0cbfa304ac856cd/src/tls_stream.rs#L648-L650)? 

Or rather, if an error occurs, tear down all the local state and avoid continuing to make progress?

**Comment by sfackler** [comment]
I don't think we want to ignore errors on our end explicitly - callers do definitely want some errors like `WouldBlock` in nonblocking land. It'd probably be best to just document on the shutdown method the conditions that should be "okay".

**Comment by alexcrichton** [comment]
Hm ok, how would callers detect this though?

The error is currently being surfaced during `Read::read` which returns "connection reset", but that's an actual error in some situations but just not an error during a shutdown?

Are you thinking that callers would query the tls stream to its current state to determine whether it's a fatal error or not?

**Comment by sfackler** [comment]
Oh, so this isn't from an explicit shutdown call, I see. I'll have to take a look over the implementation to refresh my memory of how this works again, but yeah, we'll probably want to track the state and immediately return EOF on a read if we've shut down.

**Comment by sfackler** [comment]
Ok, I think we should actually just remove this call entirely: https://github.com/steffengy/schannel-rs/blob/6899374578f8de72dae72fcdd0cbfa304ac856cd/src/tls_stream.rs#L648-L650.

I just checked OpenSSL, and it does not automatically reply to close_notify messages. Callers can explicitly call shutdown if they'd like to go through those steps, and handle errors in whatever method they'd like.
