### ISSUE TITLE
Can't connect to cert-requesting servers without client cert

### ISSUE THREAD

**Issue by jethrogb** [steffengy/schannel-rs#23]
When using this crate to connect to a TLS server that requests a client certificate, and no client certificate was configured by the program, the connection fails with the error `SEC_I_INCOMPLETE_CREDENTIALS`.

```rust
extern crate schannel;

use std::net::TcpStream;
use std::io::{self, Write};

use schannel::schannel_cred::{SchannelCred, Direction};
use schannel::tls_stream::{Builder as TlsStreamBuilder};

fn main() {
	let s = TcpStream::connect(std::env::args().nth(1).unwrap()).unwrap();
    let mut s = TlsStreamBuilder::new().connect(SchannelCred::builder().acquire(Direction::Outbound).unwrap(), s).unwrap();
	s.write_all(b"GET / HTTP/1.0\r\n\r\n").unwrap();
	io::copy(&mut s, &mut io::stdout()).unwrap();
}
```

```
$ cargo run auth.mit.edu:444
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(Error { repr: Os { code: 590624, message: "The credentials supplied were not complete, and could not be verified. Additional information can be returned from the context." } })', C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libcore\result.rs:868
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I'm actively investigating solutions.

**Comment by jethrogb** [comment]
This can be fixed by passing in `winapi::ISC_REQ_USE_SUPPLIED_CREDS` to `InitializeSecurityContextW` in `TlsStream::step_initialize`. Possibly in a second call in response to the `SEC_I_INCOMPLETE_CREDENTIALS` error. Is its non-use intentional? Not setting the flag will automatically use the system's client certificates without programmer interaction.

**Comment by steffengy** [comment]
AFAIK there isn't a reason it is not passed in. 
(except maybe suboptimal documentation)

#### 1.)

The only thing I was worried about is that we [guarantee](https://github.com/steffengy/schannel-rs/blob/17c70940dfb3fa329fe63895016a285233e8c8e2/src/schannel_cred.rs#L178) 
that added certificates are considered for client authentication.

After reading some nested layers of documentation, the only thing this flag seems to change
for that is that it reduces the search scope to the certificates linked to the handle
acquired by `AcquireCredentialsHandle`. 
So in my opinion this exactly does what we want.

### second note

From a users perspective it might be strange to get a terminated connection
from the server (when it requires a certificate but none was specified).
Not sure about a good way to improve the ergonomics here.

@sfackler

**Comment by jethrogb** [comment]
> From a users perspective it might be strange to get a terminated connection
from the server (when it requires a certificate but none was specified).

It is up to the server to terminate the connection. If it asked for a cert, but didn't get one, the server can decide to proceed as normal or abort.

**Comment by steffengy** [comment]
> It is up to the server to terminate the connection. If it asked for a cert, but didn't get one, the server can decide to proceed as normal or abort.

That's exactly the point.
A user of this library in this case cannot determine that the server aborted 
because of a missing certificate (and mitigate that by specifying one and retrying).

It could presume that but the server going offline, a firewall dropping the request, ...
would look the same.

**To recap:** The issue is an issue of ergonomics: It might happen that someone
notices a mysterious bug where the server terminates the connection.
After several hours of work and troubleshooting this someone notices that the
actual issue is a not specified client certificate.

==> The termination cause is not transparent to the user. It's hidden
and exposed as a very generic - clearly unhelpful - error for that case.

**Comment by jethrogb** [comment]
Technically, in such a case the server is to send a handshake_failure TLS alert. At least in principle, this would be distinguishable from other network-related failure modes. Whether this happens in practice and whether that level of error makes it back to the user, I don't know.
