### ISSUE TITLE
Provide access to the underlying Windows handles

### ISSUE THREAD

**Issue by Michael-F-Bryan** [steffengy/schannel-rs#58]
Would it make sense for each wrapper around a Windows type to provide an `unsafe raw()` method for getting the underlying `HANDLE`s?

For example:

```rust
impl CertStore {
  pub unsafe fn raw(&self) -> HCERTSTORE { self.0 }
}
```

The idea being that it makes interoperability with other windows APIs easier, and gives users an escape hatch if a particular feature they need isn't implemented yet.

**Comment by steffengy** [comment]
Nothing against providing access, but we can't expose winapi types.
(Else we can't update winapi without bumping schannel, which is suboptimal)
So ` -> *mut c_void` insteadof `-> HCERTSTORE`.
