### ISSUE TITLE
Switch to official Microsoft-owned windows-rs crate

### ISSUE THREAD

**Issue by ancwrd1** [steffengy/schannel-rs#75]
The winapi-rs seems to be unmaintained and in general deprecated in favor of the official Microsoft Rust project at https://github.com/microsoft/windows-rs which in turn generates it's APIs from the https://github.com/microsoft/win32metadata

I am wondering if it makes sense to switch to the official crate and if such a change would be accepted by maintainers.
I am willing to submit a PR for this.

**Comment by steffengy** [comment]
Generally no objection, as winapi isn't (and shouldnt) really be a part of our public API surface.
Might be of consequence to MSRV and unsure about windows vs windows-sys (might be closer to what we currently do).

**Comment by ancwrd1** [comment]
Thanks for your reply.

I actually tried both, `windows` and `windows-sys`, couldn't get the tests pass with the former for some reason, also it seems to have currently some issues, for example with HRESULT-returning functions (they return `Result<()>` and it's impossible to get a successful code which is a showstopper for schannel, https://github.com/microsoft/win32metadata/issues/910) and in general doesn't seem to be API-stable yet.

What is the MSRV requirement for schannel-rs? It's still at 2015 edition, would it made sense perhaps to also update it to 2018?

**Comment by steffengy** [comment]
At the moment MSRV is at `1.31.0`. The actual requirement with native-tls and other important dependents probably is something like `1.46.0`. As long as that and no other major dependents break, edition / msrv should not matter much.
